//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Create
{
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    protected global::System.Web.UI.WebControls.TextBox txtNombre;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNombre;
    protected global::System.Web.UI.WebControls.RadioButtonList rblTipoComida;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTipoComida;
    protected global::System.Web.UI.WebControls.RadioButtonList rblCalificacion;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCalificacion;
    protected global::System.Web.UI.WebControls.TextBox txtComentarios;
    protected global::System.Web.UI.WebControls.Button btnGuardar;
    protected global::System.Web.UI.WebControls.Label lblMessage;
}