//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Delete
{
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    protected global::System.Web.UI.WebControls.Panel pnlRestaurant;
    protected global::System.Web.UI.WebControls.Label lblId;
    protected global::System.Web.UI.WebControls.Label lblNombre;
    protected global::System.Web.UI.WebControls.Label lblTipoComida;
    protected global::System.Web.UI.WebControls.Label lblCalificacion;
    protected global::System.Web.UI.WebControls.Label lblComentarios;
    protected global::System.Web.UI.WebControls.Button btnEliminar;
    protected global::System.Web.UI.WebControls.Label lblMessage;
    protected global::System.Web.UI.WebControls.HiddenField hfId;
}